# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
version: 2
jobs:
  build:
    # Remove if parallelism is not desired
    parallelism: 2
test:
  override:    
    - mocha